### ISSUE TITLE
How could I let a "/" append to json_string?

### ISSUE THREAD

**Issue by Zoeyue** [karminski/streaming-json-py#1]
Hi team,

I occurred a problem when I try to using streaming-json:
When the streaming string contains a "/", then it will not be parsed in json result. For example, when I want to parse a json contains url link like "https://www.baidu.com", the final result will be "https:www.baidu.com". What should I do if I want to display the whole link?

Thanks in advance for your kindly help and efforts!

**Comment by tomasliu-agora** [comment]
I am facing the same problem when the text has '/'. is there any progress on this issue?

**Comment by karminski** [comment]
Hi guys, the bug has been fixed. Thanks for the PR by @Maplemx . Please give it a try.
